### ISSUE TITLE
Output multiple faces in single image

### ISSUE THREAD

**Issue by sobake** [leblancfg/autocrop#155] opened 2021-12-21 15:58 UTC
How can I output multiple faces in a single image? As `original_filename_1.ext, original_filename_2.ext`, etc.

**Comment by leblancfg** [comment] 2021-12-29 16:47
Hi @sobake, that's a great idea. There's no handy way of doing this currently though.

If you don't mind, I'll change the title of this issue to represent a feature request.

**Comment by leblancfg** [comment] 2022-02-11 14:43
Closing as duplicate of https://github.com/leblancfg/autocrop/issues/37.

**Closed by leblancfg** 2022-02-11 14:43 UTC
Labels: enhancement
